project:
  type: website

metadata-files:
  - _sidebar.yml

quartodoc:
  package: tathagata_ai_839
  sidebar: _sidebar.yml

website:
  navbar:
    left:
      - text: "Read The Docs"
        href: api-docs.html

sections:
  - title: Data Processing
    desc: Data processing nodes
    contents:
      - pipelines.data_processing.nodes
  - title: Data Science
    desc: Data science nodes
    contents:
      - pipelines.data_science.nodes
  - title: Pipelines
    desc: Pipeline definitions
    contents:
      - pipelines.data_processing.pipeline
      - pipelines.data_science.pipeline
  - title: Cards
    desc: Data and Model Cards
    contents:
      - data_card
      - model_card