project:
  type: website

execute:
  echo: true
  eval: true
  enabled: true
  cache: false

metadata-files:
  - _sidebar.yml

quartodoc:
  package: tathagata_ai_839
  sidebar: _sidebar.yml

website:
  navbar:
    left:
      - text: "Read The Docs"
        href: docs-quarto.html